export const CART_RETRIEVE_REQUEST = 'CART_RETRIEVE_REQUEST';
export const CART_RETRIEVE_SUCCESS = 'CART_RETRIEVE_SUCCESS';

export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';

export const CART_REMOVE = 'CART_REMOVE';

export const CART_UPDATE = 'CART_UPDATE';