export const CAPTURE_CHECKOUT_REQUEST = 'CAPTURE_CHECKOUT_REQUEST';
export const CAPTURE_CHECKOUT = 'CAPTURE_CHECKOUT';
export const ORDER_ERROR = 'ORDER_ERROR';
export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';