export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST'
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS'

export const SUBDIVISIONS_REQUEST = 'SUBDIVISIONS_REQUEST'
export const SUBDIVISIONS_SUCCESS = 'SUBDIVISIONS_SUCCESS'

export const COUNTRY_DATA = 'COUNTRY_DATA'

export const SUBDIVISION_SUCCESS = 'SUBDIVISION_SUCCESS'

export const DISTRICES_SUCCESS = 'DISTRICES_SUCCESS'

export const SUBDISTRICTS_SUCCESS = 'SUBDISTRICTS_SUCCESS'

export const DISTRICT_NAME = 'DISTRICT_NAME'