export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST'
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS'

export const SUBDIVISIONS_REQUEST = 'SUBDIVISIONS_REQUEST'
export const SUBDIVISIONS_SUCCESS = 'SUBDIVISIONS_SUCCESS'

// export const COUNTRY_DATA = 'COUNTRY_DATA'

export const SUBDIVISION_SUCCESS = 'SUBDIVISION_SUCCESS'

export const DISTRICES_SUCCESS = 'DISTRICES_SUCCESS'

export const SUBDISTRICTS_SUCCESS = 'SUBDISTRICTS_SUCCESS'

export const OPTIONS_SUCCESS = 'OPTIONS_SUCCESS'

export const SET_SUBDIVISION_ID = 'SET_SUBDIVISION_ID'
export const SET_DISTRICT_NAME_ID = 'SET_DISTRICT_NAME_ID'
export const SET_SUBDISTRICT_NAME_ID = 'SET_SUBDISTRICT_NAME_ID'
export const SET_OPTION_ID = 'SET_OPTION_ID'