export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST'
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS'

export const SUBDIVISIONS_REQUEST = 'SUBDIVISIONS_REQUEST'
export const SUBDIVISIONS_SUCCESS = 'SUBDIVISIONS_SUCCESS'

export const COUNTRY_DATA = 'COUNTRY_DATA'